### ISSUE TITLE
Unable to use offline

### ISSUE THREAD

**Issue by beruic** [HJ29/vue3-qr-reader#2]
I'm working on a Capacitor app project where want to use `vue3-qr-reader` (because it works great).
However in order to do so, we need to load `jsQR` locally.

Unfortunately <https://cdn.jsdelivr.net/npm/jsqr@1.3.1/dist/jsQR.min.js> is hard-coded in `src/worker/jsqr.js`.

Can it somehow be made configurable?

Another problem we have is that we have to add <https://cdn.jsdelivr.net/> to our Content-Security-Policy, which is not good.

**Comment by HJ29** [comment]
Hi, thanks for reporting this issue.
this package is basically a clone from https://github.com/gruhn/vue-qrcode-reader, but with vue 3 syntax.
here is the issue https://github.com/gruhn/vue-qrcode-reader/issues/197
there are some workaround suggested from the owner of package, if u urgently need to do this, u can give it a try. I didn't try it out before, so i am not sure if those workaround is working and compatible with this package. 

btw, since v3.0.0 of the original package stop using worker, replaced by https://www.npmjs.com/package/barcode-detector polyfill.
I am going to implement this too, but i don't have a deadline, maybe this weekend, maybe not.

**Comment by beruic** [comment]
For now I have patched this in our build system.

Just want to share this with you, as I think it could be helpful:
For relative URLs you need to prepend them with `location.origin +`. E.g. `location.origin + "/scripts/jsqr/jsQR.js"`.

**Comment by HJ29** [comment]
v1.0.0 removed dependency on https://cdn.jsdelivr.net/npm/jsqr@1.3.1/dist/jsQR.min.js
